// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTAp3HrQ9Egjlih9yNpi0aUAKp355xFY',
    appId: '1:913556527908:web:d8703c1860530b53c371b1',
    messagingSenderId: '913556527908',
    projectId: 'exam-dd575',
    authDomain: 'exam-dd575.firebaseapp.com',
    storageBucket: 'exam-dd575.appspot.com',
    measurementId: 'G-179V15BGHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHvAVYKk5DLm1b5_5ALscwOAP619G8Ib8',
    appId: '1:913556527908:android:497f747a018bd78fc371b1',
    messagingSenderId: '913556527908',
    projectId: 'exam-dd575',
    storageBucket: 'exam-dd575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTrBt_P-FYqnPiNaH8L5jxLfYCLZGotI',
    appId: '1:913556527908:ios:b1107725b84fc572c371b1',
    messagingSenderId: '913556527908',
    projectId: 'exam-dd575',
    storageBucket: 'exam-dd575.appspot.com',
    iosBundleId: 'com.example.secExamAdv',
  );
}
